#!/bin/sh

if [ ! -d "otter" ]; then
	#git clone git@github.com:philipclaude/otter.git
	curl -O https://philipclaude.github.io/otter/otter.zip
	unzip -d otter otter.zip
fi
python otter/otter.py --check all
