name: Checks

on:
  push:
    branches: main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Lint
      run: |
        pylint otter.py
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  
    - name: Install Dependencies
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        architecture: x64
    - name: Test
      run: |
        cd example
        ./check
